### PR TITLE
Lambda Expressions and Approximation of Roots

### PR DESCRIPTION
**Pull request by glyphrider**
I was intrigued by the discussions we had Monday night regrading _closures_ and refining of code. I noticed that there was a lot of discussion in the lecture(s) regarding approximation of square roots followed by an exercise in approximating cube roots. So, I spent a little time working an evolution from the initial square root idea, to a _generic_ approximation engine that can work through any problem.

**What do you guys think?**

### CODE REVIEW

**Comment by glyphrider** [comment]
@RickBacci -- you are exactly correct. The `abs` and `avg` functions never made it *inside* the `sqrt` function, because they were mere building blocks (which also had potential use outside of the approximation domain). The *lambda expressions* don't need to be named, because they are used to evolve the approximate function into performing square root approximation (or later, cube root approximation); they receive names when they are bound to the formal parameters of the approximate function.

**Comment by jonknapp** [comment]
yea boy!  thank you very much for the end result and especially for the path to get there.

**Comment by RickBacci** [comment]
@glyphrider Not be be a total noob, but do i have to merge this?

**Comment by jonknapp** [comment]
The pull request was a way to show his changes in one place for review. It
doesn't have to be merged unless he does not have commit access to the repo.

**Comment by RickBacci** [comment]
@jonknapp thanks

**Pull request merged**
